=begin
#Rippling Platform API

#Documentation for the Rippling Platform API.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'

# Unit tests for RipplingRb::CompensationsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CompensationsApi' do
  before do
    # run before each test
    @api_instance = RipplingRb::CompensationsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CompensationsApi' do
    it 'should create an instance of CompensationsApi' do
      expect(@api_instance).to be_instance_of(RipplingRb::CompensationsApi)
    end
  end

  # unit tests for get_compensations
  # Retrieve a specific compensation
  # Retrieves the Compensation for the Worker with the ID provided in the URL path.
  # @param id ID of the resource to return
  # @param [Hash] opts the optional parameters
  # @option opts [String] :expand 
  # @return [GetCompensations200Response]
  describe 'get_compensations test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_compensations
  # List compensations
  # A List of compensations  - Requires: &#x60;API Tier 2&#x60;  - Expandable fields: &#x60;worker&#x60;  - Sortable fields: &#x60;id&#x60;, &#x60;created_at&#x60;, &#x60;updated_at&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :expand 
  # @option opts [String] :order_by 
  # @return [ListCompensations200Response]
  describe 'list_compensations test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
