=begin
#Rippling Platform API

#Documentation for the Rippling Platform API.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'

# Unit tests for RipplingRb::CustomObjectFieldsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CustomObjectFieldsApi' do
  before do
    # run before each test
    @api_instance = RipplingRb::CustomObjectFieldsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CustomObjectFieldsApi' do
    it 'should create an instance of CustomObjectFieldsApi' do
      expect(@api_instance).to be_instance_of(RipplingRb::CustomObjectFieldsApi)
    end
  end

  # unit tests for create_custom_objects__custom_object_api_name_fields
  # Create a new custom object field
  # Create a new custom object field
  # @param custom_object_api_name 
  # @param [Hash] opts the optional parameters
  # @option opts [CreateCustomObjectsCustomObjectApiNameFieldsRequest] :create_custom_objects_custom_object_api_name_fields_request 
  # @return [CustomObjectField]
  describe 'create_custom_objects__custom_object_api_name_fields test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_custom_objects__custom_object_api_name_fields
  # Delete a custom object field
  # Delete a custom object field
  # @param custom_object_api_name 
  # @param field_api_name 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_custom_objects__custom_object_api_name_fields test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_custom_objects__custom_object_api_name_fields
  # Retrieve a specific custom object field
  # Retrieve a specific custom object field
  # @param custom_object_api_name 
  # @param field_api_name 
  # @param [Hash] opts the optional parameters
  # @return [CustomObjectField]
  describe 'get_custom_objects__custom_object_api_name_fields test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_custom_objects__custom_object_api_name_fields
  # List custom object fields
  # A List of custom object fields  - Requires: &#x60;API Tier 1&#x60;
  # @param custom_object_api_name 
  # @param [Hash] opts the optional parameters
  # @return [ListCustomObjectsCustomObjectApiNameFields200Response]
  describe 'list_custom_objects__custom_object_api_name_fields test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_custom_objects__custom_object_api_name_fields
  # Update a custom object field
  # Updated a specific custom object field
  # @param custom_object_api_name 
  # @param field_api_name 
  # @param [Hash] opts the optional parameters
  # @option opts [UpdateCustomObjectsCustomObjectApiNameFieldsRequest] :update_custom_objects_custom_object_api_name_fields_request 
  # @return [CustomObjectField]
  describe 'update_custom_objects__custom_object_api_name_fields test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
