=begin
#Rippling Platform API

#Documentation for the Rippling Platform API.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'

# Unit tests for RipplingRb::CustomObjectRecordsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CustomObjectRecordsApi' do
  before do
    # run before each test
    @api_instance = RipplingRb::CustomObjectRecordsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CustomObjectRecordsApi' do
    it 'should create an instance of CustomObjectRecordsApi' do
      expect(@api_instance).to be_instance_of(RipplingRb::CustomObjectRecordsApi)
    end
  end

  # unit tests for bulk_create_custom_objects__custom_object_api_name_records
  # Bulk Create custom object records
  # bulk create new custom object records
  # @param custom_object_api_name 
  # @param [Hash] opts the optional parameters
  # @option opts [BulkCreateCustomObjectsCustomObjectApiNameRecordsRequest] :bulk_create_custom_objects_custom_object_api_name_records_request 
  # @return [BulkCreateCustomObjectsCustomObjectApiNameRecords200Response]
  describe 'bulk_create_custom_objects__custom_object_api_name_records test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for bulk_delete_custom_objects__custom_object_api_name_records
  # Bulk delete custom object records
  # Bulk Delete custom object records
  # @param custom_object_api_name 
  # @param [Hash] opts the optional parameters
  # @option opts [BulkDeleteCustomObjectsCustomObjectApiNameRecordsRequest] :bulk_delete_custom_objects_custom_object_api_name_records_request 
  # @return [nil]
  describe 'bulk_delete_custom_objects__custom_object_api_name_records test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for bulk_update_custom_objects__custom_object_api_name_records
  # Bulk Update custom object records
  # Bulk Updated a specific custom object records
  # @param custom_object_api_name 
  # @param [Hash] opts the optional parameters
  # @option opts [BulkUpdateCustomObjectsCustomObjectApiNameRecordsRequest] :bulk_update_custom_objects_custom_object_api_name_records_request 
  # @return [BulkCreateCustomObjectsCustomObjectApiNameRecords200Response]
  describe 'bulk_update_custom_objects__custom_object_api_name_records test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_custom_objects__custom_object_api_name_records
  # Create a new custom object record
  # Create a new custom object record
  # @param custom_object_api_name 
  # @param [Hash] opts the optional parameters
  # @option opts [Hash<String, Object>] :request_body 
  # @return [CreateCustomObjectsCustomObjectApiNameRecords200Response]
  describe 'create_custom_objects__custom_object_api_name_records test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_custom_objects__custom_object_api_name_records
  # Delete a custom object record
  # @param custom_object_api_name 
  # @param codr_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_custom_objects__custom_object_api_name_records test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_custom_objects__custom_object_api_name_records
  # Retrieve a specific custom object record
  # Retrieve a specific custom object record
  # @param custom_object_api_name 
  # @param codr_id 
  # @param [Hash] opts the optional parameters
  # @return [CustomObjectDataRow]
  describe 'get_custom_objects__custom_object_api_name_records test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_custom_objects__custom_object_api_name_records_by_external_id
  # Retrieve a specific custom object record by its external_id
  # Retrieve a specific custom object record by its external_id
  # @param custom_object_api_name 
  # @param external_id 
  # @param [Hash] opts the optional parameters
  # @return [CustomObjectDataRow]
  describe 'get_custom_objects__custom_object_api_name_records_by_external_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_by_query_custom_objects__custom_object_api_name_records
  # List custom object records by query
  # A List of custom object records filtered by querying
  # @param custom_object_api_name 
  # @param [Hash] opts the optional parameters
  # @option opts [ListByQueryCustomObjectsCustomObjectApiNameRecordsRequest] :list_by_query_custom_objects_custom_object_api_name_records_request 
  # @return [ListByQueryCustomObjectsCustomObjectApiNameRecords200Response]
  describe 'list_by_query_custom_objects__custom_object_api_name_records test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_custom_objects__custom_object_api_name_records
  # List custom object records
  # A List of custom object records  - Requires: &#x60;API Tier 1&#x60;
  # @param custom_object_api_name 
  # @param [Hash] opts the optional parameters
  # @return [ListCustomObjectsCustomObjectApiNameRecords200Response]
  describe 'list_custom_objects__custom_object_api_name_records test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_custom_objects__custom_object_api_name_records
  # Update a custom object record
  # Updated a specific custom object record
  # @param custom_object_api_name 
  # @param codr_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Hash<String, Object>] :request_body 
  # @return [CreateCustomObjectsCustomObjectApiNameRecords200Response]
  describe 'update_custom_objects__custom_object_api_name_records test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
