=begin
#Rippling Platform API

#Documentation for the Rippling Platform API.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'

# Unit tests for RipplingRb::CustomObjectsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CustomObjectsApi' do
  before do
    # run before each test
    @api_instance = RipplingRb::CustomObjectsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CustomObjectsApi' do
    it 'should create an instance of CustomObjectsApi' do
      expect(@api_instance).to be_instance_of(RipplingRb::CustomObjectsApi)
    end
  end

  # unit tests for create_custom_objects
  # Create a new custom object
  # Create a new custom object
  # @param [Hash] opts the optional parameters
  # @option opts [CreateCustomObjectsRequest] :create_custom_objects_request 
  # @return [CustomObject]
  describe 'create_custom_objects test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_custom_objects
  # Delete a custom object
  # @param custom_object_api_name 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_custom_objects test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_custom_objects
  # Retrieve a specific custom object
  # Retrieve a specific custom object
  # @param custom_object_api_name 
  # @param [Hash] opts the optional parameters
  # @return [CustomObject]
  describe 'get_custom_objects test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_custom_objects
  # List custom objects
  # A List of custom objects  - Requires: &#x60;API Tier 1&#x60;
  # @param [Hash] opts the optional parameters
  # @return [ListCustomObjects200Response]
  describe 'list_custom_objects test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_custom_objects
  # Update a custom object
  # Updated a specific custom object
  # @param custom_object_api_name 
  # @param [Hash] opts the optional parameters
  # @option opts [UpdateCustomObjectsRequest] :update_custom_objects_request 
  # @return [CustomObject]
  describe 'update_custom_objects test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
