=begin
#Rippling Platform API

#Documentation for the Rippling Platform API.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::EmploymentTypesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'EmploymentTypesApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::EmploymentTypesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of EmploymentTypesApi' do
    it 'should create an instance of EmploymentTypesApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::EmploymentTypesApi)
    end
  end

  # unit tests for get_employment_types
  # Retrieve a specific employment type
  # Retrieve a specific employment type
  # @param id ID of the resource to return
  # @param [Hash] opts the optional parameters
  # @return [GetEmploymentTypes200Response]
  describe 'get_employment_types test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_employment_types
  # List employment types
  # A List of employment types  - Requires: &#x60;API Tier 1&#x60;  - Sortable fields: &#x60;id&#x60;, &#x60;created_at&#x60;, &#x60;updated_at&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :order_by 
  # @return [ListEmploymentTypes200Response]
  describe 'list_employment_types test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
