=begin
#Rippling Platform API

#Documentation for the Rippling Platform API.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'

# Unit tests for RipplingRb::JobApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'JobApi' do
  before do
    # run before each test
    @api_instance = RipplingRb::JobApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of JobApi' do
    it 'should create an instance of JobApi' do
      expect(@api_instance).to be_instance_of(RipplingRb::JobApi)
    end
  end

  # unit tests for create_job_codes
  # Create a new job code
  # Create a new job code
  # @param [Hash] opts the optional parameters
  # @option opts [JobCodeRequest] :job_code_request 
  # @return [JobCode]
  describe 'create_job_codes test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_job_dimensions
  # Create a new job dimension
  # Create a new job dimension
  # @param [Hash] opts the optional parameters
  # @option opts [JobDimensionRequest] :job_dimension_request 
  # @return [JobDimension]
  describe 'create_job_dimensions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_job_codes
  # Delete a job code
  # @param id ID of the resource to delete
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_job_codes test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_job_dimensions
  # Delete a job dimension
  # @param id ID of the resource to delete
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_job_dimensions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_job_codes
  # Retrieve a specific job code
  # Retrieve a specific job code
  # @param id ID of the resource to return
  # @param [Hash] opts the optional parameters
  # @option opts [String] :expand 
  # @return [GetJobCodes200Response]
  describe 'get_job_codes test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_job_dimensions
  # Retrieve a specific job dimension
  # Retrieve a specific job dimension
  # @param id ID of the resource to return
  # @param [Hash] opts the optional parameters
  # @return [GetJobDimensions200Response]
  describe 'get_job_dimensions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_job_codes
  # List job codes
  # A List of job codes  - Requires: &#x60;API Tier 2&#x60;  - Filterable fields: &#x60;job_dimension_id&#x60;, &#x60;group_id&#x60;  - Expandable fields: &#x60;job_dimension&#x60;  - Sortable fields: &#x60;id&#x60;, &#x60;created_at&#x60;, &#x60;updated_at&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :filter 
  # @option opts [String] :expand 
  # @option opts [String] :order_by 
  # @return [ListJobCodes200Response]
  describe 'list_job_codes test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_job_dimensions
  # List job dimensions
  # A List of job dimensions  - Requires: &#x60;API Tier 2&#x60;  - Filterable fields: &#x60;name&#x60;  - Sortable fields: &#x60;id&#x60;, &#x60;created_at&#x60;, &#x60;updated_at&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :filter 
  # @option opts [String] :order_by 
  # @return [ListJobDimensions200Response]
  describe 'list_job_dimensions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_job_codes
  # Update a job code
  # Updated a specific job code
  # @param id ID of the resource to patch
  # @param [Hash] opts the optional parameters
  # @option opts [JobCodeRequest] :job_code_request 
  # @return [JobCode]
  describe 'update_job_codes test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_job_dimensions
  # Update a job dimension
  # Updated a specific job dimension
  # @param id ID of the resource to patch
  # @param [Hash] opts the optional parameters
  # @option opts [JobDimensionRequest] :job_dimension_request 
  # @return [JobDimension]
  describe 'update_job_dimensions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
