=begin
#Rippling Platform API

#Documentation for the Rippling Platform API.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'

# Unit tests for RipplingRb::LegalEntitiesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'LegalEntitiesApi' do
  before do
    # run before each test
    @api_instance = RipplingRb::LegalEntitiesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LegalEntitiesApi' do
    it 'should create an instance of LegalEntitiesApi' do
      expect(@api_instance).to be_instance_of(RipplingRb::LegalEntitiesApi)
    end
  end

  # unit tests for get_legal_entities
  # Retrieve a specific legal entity
  # Retrieve a specific legal entity
  # @param id ID of the resource to return
  # @param [Hash] opts the optional parameters
  # @option opts [String] :expand 
  # @return [GetLegalEntities200Response]
  describe 'get_legal_entities test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_legal_entities
  # List legal entities
  # A List of legal entities  - Requires: &#x60;API Tier 2&#x60;  - Expandable fields: &#x60;parent&#x60;, &#x60;company&#x60;  - Sortable fields: &#x60;id&#x60;, &#x60;created_at&#x60;, &#x60;updated_at&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :expand 
  # @option opts [String] :order_by 
  # @return [ListLegalEntities200Response]
  describe 'list_legal_entities test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
