=begin
#Rippling Platform API

#Documentation for the Rippling Platform API.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::MeApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'MeApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::MeApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MeApi' do
    it 'should create an instance of MeApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::MeApi)
    end
  end

  # unit tests for list_sso_me
  # Retrieve my SSO information
  # SSO information of the current user  - Requires: &#x60;API Tier 1&#x60;  - Expandable fields: &#x60;company&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :expand 
  # @return [SSOMe]
  describe 'list_sso_me test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
