=begin
#Rippling Platform API

#Documentation for the Rippling Platform API.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::ObjectCategoriesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ObjectCategoriesApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::ObjectCategoriesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ObjectCategoriesApi' do
    it 'should create an instance of ObjectCategoriesApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::ObjectCategoriesApi)
    end
  end

  # unit tests for create_object_categories
  # Create a new object category
  # Create a new object category
  # @param [Hash] opts the optional parameters
  # @option opts [CreateObjectCategoriesRequest] :create_object_categories_request 
  # @return [ObjectCategory]
  describe 'create_object_categories test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_object_categories
  # Delete a object category
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_object_categories test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_object_categories
  # Retrieve a specific object category
  # Retrieve a specific object category
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [ObjectCategory]
  describe 'get_object_categories test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_object_categories
  # List object categories
  # A List of object categories  - Requires: &#x60;API Tier 1&#x60;
  # @param [Hash] opts the optional parameters
  # @return [ListObjectCategories200Response]
  describe 'list_object_categories test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_object_categories
  # Update a object category
  # Updated a specific object category
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [CreateObjectCategoriesRequest] :create_object_categories_request 
  # @return [ObjectCategory]
  describe 'update_object_categories test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
