=begin
#Rippling Platform API

#Documentation for the Rippling Platform API.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'

# Unit tests for RipplingRb::ShiftInputsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ShiftInputsApi' do
  before do
    # run before each test
    @api_instance = RipplingRb::ShiftInputsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ShiftInputsApi' do
    it 'should create an instance of ShiftInputsApi' do
      expect(@api_instance).to be_instance_of(RipplingRb::ShiftInputsApi)
    end
  end

  # unit tests for create_shift_inputs
  # Create a new shift input
  # Create a new shift input
  # @param [Hash] opts the optional parameters
  # @option opts [ShiftInputRequest] :shift_input_request 
  # @return [ShiftInput]
  describe 'create_shift_inputs test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_shift_inputs
  # Delete a shift input
  # @param id ID of the resource to delete
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_shift_inputs test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_shift_inputs
  # Retrieve a specific shift input
  # Retrieve a specific shift input
  # @param id ID of the resource to return
  # @param [Hash] opts the optional parameters
  # @option opts [String] :expand 
  # @return [GetShiftInputs200Response]
  describe 'get_shift_inputs test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_shift_inputs
  # List shift inputs
  # A List of shift inputs  - Requires: &#x60;API Tier 2&#x60;  - Filterable fields: &#x60;name&#x60;  - Expandable fields: &#x60;creator&#x60;  - Sortable fields: &#x60;id&#x60;, &#x60;created_at&#x60;, &#x60;updated_at&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :filter 
  # @option opts [String] :expand 
  # @option opts [String] :order_by 
  # @return [ListShiftInputs200Response]
  describe 'list_shift_inputs test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_shift_inputs
  # Update a shift input
  # Updated a specific shift input
  # @param id ID of the resource to patch
  # @param [Hash] opts the optional parameters
  # @option opts [ShiftInputRequest] :shift_input_request 
  # @return [ShiftInput]
  describe 'update_shift_inputs test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
