=begin
#Rippling Platform API

#Documentation for the Rippling Platform API.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'

# Unit tests for RipplingRb::SupergroupsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SupergroupsApi' do
  before do
    # run before each test
    @api_instance = RipplingRb::SupergroupsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SupergroupsApi' do
    it 'should create an instance of SupergroupsApi' do
      expect(@api_instance).to be_instance_of(RipplingRb::SupergroupsApi)
    end
  end

  # unit tests for get_supergroups
  # Retrieve a specific supergroup
  # Retrieve a specific supergroup.
  # @param id ID of the resource to return
  # @param [Hash] opts the optional parameters
  # @return [GetSupergroups200Response]
  describe 'get_supergroups test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_supergroups
  # List supergroups
  # Retrieve supergroups matching the input parameters.  - Requires: &#x60;API Tier 1&#x60;  - Filterable fields: &#x60;app_owner_id&#x60;, &#x60;group_type&#x60;  - Sortable fields: &#x60;id&#x60;, &#x60;created_at&#x60;, &#x60;updated_at&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :filter 
  # @option opts [String] :order_by 
  # @return [ListSupergroups200Response]
  describe 'list_supergroups test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_supergroups__group_id_exclusion_members
  # List supergroup exclusion members
  # Retrieve supergroup exclusion members matching the input parameters.  - Requires: &#x60;API Tier 1&#x60;  - Sortable fields: &#x60;id&#x60;, &#x60;created_at&#x60;, &#x60;updated_at&#x60;
  # @param group_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :order_by 
  # @return [ListSupergroupsGroupIdMembers200Response]
  describe 'list_supergroups__group_id_exclusion_members test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_supergroups__group_id_inclusion_members
  # List supergroup inclusion members
  # Retrieve supergroup inclusion members matching the input parameters.  - Requires: &#x60;API Tier 1&#x60;  - Sortable fields: &#x60;id&#x60;, &#x60;created_at&#x60;, &#x60;updated_at&#x60;
  # @param group_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :order_by 
  # @return [ListSupergroupsGroupIdMembers200Response]
  describe 'list_supergroups__group_id_inclusion_members test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_supergroups__group_id_members
  # List supergroup members
  # Retrieve supergroup members matching the input parameters.  - Requires: &#x60;API Tier 1&#x60;  - Sortable fields: &#x60;id&#x60;, &#x60;created_at&#x60;, &#x60;updated_at&#x60;
  # @param group_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :order_by 
  # @return [ListSupergroupsGroupIdMembers200Response]
  describe 'list_supergroups__group_id_members test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_supergroups__group_id_exclusion_members
  # Update supergroup exclusion members
  # Update the list of supergroup exclusion members.
  # @param group_id 
  # @param [Hash] opts the optional parameters
  # @option opts [UpdateSupergroupsGroupIdInclusionMembersRequest] :update_supergroups_group_id_inclusion_members_request 
  # @return [UpdateSupergroupsGroupIdInclusionMembers200Response]
  describe 'update_supergroups__group_id_exclusion_members test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_supergroups__group_id_inclusion_members
  # Update supergroup inclusion members
  # Update the list of supergroup inclusion members.
  # @param group_id 
  # @param [Hash] opts the optional parameters
  # @option opts [UpdateSupergroupsGroupIdInclusionMembersRequest] :update_supergroups_group_id_inclusion_members_request 
  # @return [UpdateSupergroupsGroupIdInclusionMembers200Response]
  describe 'update_supergroups__group_id_inclusion_members test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
