=begin
#Rippling Platform API

#Documentation for the Rippling Platform API.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'

# Unit tests for RipplingRb::TimeEntriesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TimeEntriesApi' do
  before do
    # run before each test
    @api_instance = RipplingRb::TimeEntriesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TimeEntriesApi' do
    it 'should create an instance of TimeEntriesApi' do
      expect(@api_instance).to be_instance_of(RipplingRb::TimeEntriesApi)
    end
  end

  # unit tests for create_time_entries
  # Create a new time entry
  # Create a new time entry
  # @param [Hash] opts the optional parameters
  # @option opts [TimeEntryRequest] :time_entry_request 
  # @return [TimeEntry]
  describe 'create_time_entries test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_time_entries
  # Delete a time entry
  # @param id ID of the resource to delete
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_time_entries test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_time_cards
  # Retrieve a specific time card
  # Retrieve a specific time card
  # @param id ID of the resource to return
  # @param [Hash] opts the optional parameters
  # @option opts [String] :expand 
  # @return [GetTimeCards200Response]
  describe 'get_time_cards test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_time_entries
  # Retrieve a specific time entry
  # Retrieve a specific time entry
  # @param id ID of the resource to return
  # @param [Hash] opts the optional parameters
  # @option opts [String] :expand 
  # @return [GetTimeEntries200Response]
  describe 'get_time_entries test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_time_cards
  # List time cards
  # A List of time cards  - Requires: &#x60;API Tier 2&#x60;  - Filterable fields: &#x60;pay_period.start_date&#x60;, &#x60;worker_id&#x60;  - Expandable fields: &#x60;worker&#x60;  - Sortable fields: &#x60;id&#x60;, &#x60;created_at&#x60;, &#x60;updated_at&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :filter 
  # @option opts [String] :expand 
  # @option opts [String] :order_by 
  # @return [ListTimeCards200Response]
  describe 'list_time_cards test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_time_entries
  # List time entries
  # A List of time entries  - Requires: &#x60;API Tier 2&#x60;  - Filterable fields: &#x60;worker_id&#x60;, &#x60;start_time&#x60;, &#x60;pay_period.start_date&#x60;  - Expandable fields: &#x60;worker&#x60;, &#x60;time_card&#x60;  - Sortable fields: &#x60;id&#x60;, &#x60;created_at&#x60;, &#x60;updated_at&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :filter 
  # @option opts [String] :expand 
  # @option opts [String] :order_by 
  # @return [ListTimeEntries200Response]
  describe 'list_time_entries test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_time_entries
  # Update a time entry
  # Updated a specific time entry
  # @param id ID of the resource to patch
  # @param [Hash] opts the optional parameters
  # @option opts [TimeEntryRequest] :time_entry_request 
  # @return [TimeEntry]
  describe 'update_time_entries test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
