=begin
#Rippling Platform API

#Documentation for the Rippling Platform API.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'

# Unit tests for RipplingRb::TracksAndLevelsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TracksAndLevelsApi' do
  before do
    # run before each test
    @api_instance = RipplingRb::TracksAndLevelsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TracksAndLevelsApi' do
    it 'should create an instance of TracksAndLevelsApi' do
      expect(@api_instance).to be_instance_of(RipplingRb::TracksAndLevelsApi)
    end
  end

  # unit tests for get_levels
  # Retrieve a specific level
  # Retrieve a specific level
  # @param id ID of the resource to return
  # @param [Hash] opts the optional parameters
  # @option opts [String] :expand 
  # @return [GetLevels200Response]
  describe 'get_levels test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_tracks
  # Retrieve a specific track
  # Retrieve a specific track
  # @param id ID of the resource to return
  # @param [Hash] opts the optional parameters
  # @return [GetTracks200Response]
  describe 'get_tracks test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_levels
  # List levels
  # A List of levels  - Requires: &#x60;API Tier 2&#x60;  - Expandable fields: &#x60;parent&#x60;, &#x60;track&#x60;  - Sortable fields: &#x60;id&#x60;, &#x60;created_at&#x60;, &#x60;updated_at&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :expand 
  # @option opts [String] :order_by 
  # @return [ListLevels200Response]
  describe 'list_levels test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_tracks
  # List tracks
  # A List of tracks  - Requires: &#x60;API Tier 2&#x60;  - Sortable fields: &#x60;id&#x60;, &#x60;created_at&#x60;, &#x60;updated_at&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :order_by 
  # @return [ListTracks200Response]
  describe 'list_tracks test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
