=begin
#Rippling Platform API

#Documentation for the Rippling Platform API.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for RipplingRb::BulkDeleteCustomObjectsCustomObjectApiNameRecordsRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe RipplingRb::BulkDeleteCustomObjectsCustomObjectApiNameRecordsRequest do
  let(:instance) { RipplingRb::BulkDeleteCustomObjectsCustomObjectApiNameRecordsRequest.new }

  describe 'test an instance of BulkDeleteCustomObjectsCustomObjectApiNameRecordsRequest' do
    it 'should create an instance of BulkDeleteCustomObjectsCustomObjectApiNameRecordsRequest' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(RipplingRb::BulkDeleteCustomObjectsCustomObjectApiNameRecordsRequest)
    end
  end

  describe 'test attribute "rows_to_delete"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "all_or_nothing"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
