=begin
#Rippling Platform API

#Documentation for the Rippling Platform API.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::CountryFields
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::CountryFields do
  let(:instance) { OpenapiClient::CountryFields.new }

  describe 'test an instance of CountryFields' do
    it 'should create an instance of CountryFields' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::CountryFields)
    end
  end

  describe 'test attribute "us"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "ca"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
