=begin
#Rippling Platform API

#Documentation for the Rippling Platform API.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for RipplingRb::JobDimensionRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe RipplingRb::JobDimensionRequest do
  let(:instance) { RipplingRb::JobDimensionRequest.new }

  describe 'test an instance of JobDimensionRequest' do
    it 'should create an instance of JobDimensionRequest' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(RipplingRb::JobDimensionRequest)
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "external_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "includes_custom_location"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "roster_type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["PER_DIMENSION", "PER_JOB_CODE"])
      # validator.allowable_values.each do |value|
      #   expect { instance.roster_type = value }.not_to raise_error
      # end
    end
  end

end
