=begin
#Rippling Platform API

#Documentation for the Rippling Platform API.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::ListUsers200Response
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::ListUsers200Response do
  let(:instance) { OpenapiClient::ListUsers200Response.new }

  describe 'test an instance of ListUsers200Response' do
    it 'should create an instance of ListUsers200Response' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::ListUsers200Response)
    end
  end

  describe 'test attribute "__meta"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "results"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "next_link"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
