=begin
#Rippling Platform API

#Documentation for the Rippling Platform API.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

# Common files
require 'openapi_client/api_client'
require 'openapi_client/api_error'
require 'openapi_client/version'
require 'openapi_client/configuration'

# Models
require 'openapi_client/models/address'
require 'openapi_client/models/address_request'
require 'openapi_client/models/application'
require 'openapi_client/models/break_request'
require 'openapi_client/models/bulk_create_custom_objects_custom_object_api_name_records200_response'
require 'openapi_client/models/bulk_create_custom_objects_custom_object_api_name_records_request'
require 'openapi_client/models/bulk_delete_custom_objects_custom_object_api_name_records_request'
require 'openapi_client/models/bulk_update_custom_objects_custom_object_api_name_records_request'
require 'openapi_client/models/canada_fields'
require 'openapi_client/models/candidate'
require 'openapi_client/models/company'
require 'openapi_client/models/company_employment_type'
require 'openapi_client/models/compensation'
require 'openapi_client/models/country'
require 'openapi_client/models/country_fields'
require 'openapi_client/models/create_custom_objects_custom_object_api_name_fields_request'
require 'openapi_client/models/create_custom_objects_custom_object_api_name_records200_response'
require 'openapi_client/models/create_custom_objects_request'
require 'openapi_client/models/create_object_categories_request'
require 'openapi_client/models/currency'
require 'openapi_client/models/custom_field'
require 'openapi_client/models/custom_location'
require 'openapi_client/models/custom_location_request'
require 'openapi_client/models/custom_object'
require 'openapi_client/models/custom_object_data_row'
require 'openapi_client/models/custom_object_data_row_created_by'
require 'openapi_client/models/custom_object_field'
require 'openapi_client/models/day_off'
require 'openapi_client/models/department'
require 'openapi_client/models/email'
require 'openapi_client/models/entitlement_model'
require 'openapi_client/models/get_departments200_response'
require 'openapi_client/models/get_employment_types200_response'
require 'openapi_client/models/get_supergroups200_response'
require 'openapi_client/models/get_teams200_response'
require 'openapi_client/models/get_users200_response'
require 'openapi_client/models/get_work_locations200_response'
require 'openapi_client/models/get_workers200_response'
require 'openapi_client/models/group_member'
require 'openapi_client/models/job_code'
require 'openapi_client/models/job_code_summary'
require 'openapi_client/models/job_dimension'
require 'openapi_client/models/job_requisition'
require 'openapi_client/models/job_shift'
require 'openapi_client/models/job_shift_request'
require 'openapi_client/models/leave_balance'
require 'openapi_client/models/leave_request'
require 'openapi_client/models/leave_type'
require 'openapi_client/models/legal_entity'
require 'openapi_client/models/level'
require 'openapi_client/models/list_by_query_custom_objects_custom_object_api_name_records200_response'
require 'openapi_client/models/list_by_query_custom_objects_custom_object_api_name_records_request'
require 'openapi_client/models/list_companies200_response'
require 'openapi_client/models/list_custom_fields200_response'
require 'openapi_client/models/list_custom_objects200_response'
require 'openapi_client/models/list_custom_objects_custom_object_api_name_fields200_response'
require 'openapi_client/models/list_custom_objects_custom_object_api_name_records200_response'
require 'openapi_client/models/list_departments200_response'
require 'openapi_client/models/list_employment_types200_response'
require 'openapi_client/models/list_entitlements200_response'
require 'openapi_client/models/list_object_categories200_response'
require 'openapi_client/models/list_supergroups200_response'
require 'openapi_client/models/list_supergroups_group_id_members200_response'
require 'openapi_client/models/list_teams200_response'
require 'openapi_client/models/list_users200_response'
require 'openapi_client/models/list_work_locations200_response'
require 'openapi_client/models/list_workers200_response'
require 'openapi_client/models/meta_response'
require 'openapi_client/models/meta_response_meta'
require 'openapi_client/models/model_break'
require 'openapi_client/models/object_category'
require 'openapi_client/models/pay_period'
require 'openapi_client/models/pay_period_request'
require 'openapi_client/models/piece_rate_premiums'
require 'openapi_client/models/premiums'
require 'openapi_client/models/prototype_job'
require 'openapi_client/models/prototype_work_location'
require 'openapi_client/models/redacted_field'
require 'openapi_client/models/redacted_fields'
require 'openapi_client/models/redacted_fields_redacted_fields_inner'
require 'openapi_client/models/ssome'
require 'openapi_client/models/segments'
require 'openapi_client/models/shift_input'
require 'openapi_client/models/shift_input_value'
require 'openapi_client/models/shift_input_value_request'
require 'openapi_client/models/supergroup'
require 'openapi_client/models/team'
require 'openapi_client/models/termination_details'
require 'openapi_client/models/time_card'
require 'openapi_client/models/time_card_summary'
require 'openapi_client/models/time_entry'
require 'openapi_client/models/time_entry_comment'
require 'openapi_client/models/time_entry_comment_request'
require 'openapi_client/models/time_entry_summary'
require 'openapi_client/models/time_kiosk_badge'
require 'openapi_client/models/track'
require 'openapi_client/models/us_fields'
require 'openapi_client/models/update_custom_objects_custom_object_api_name_fields_request'
require 'openapi_client/models/update_custom_objects_request'
require 'openapi_client/models/update_supergroups_group_id_inclusion_members200_response'
require 'openapi_client/models/update_supergroups_group_id_inclusion_members_request'
require 'openapi_client/models/update_supergroups_group_id_inclusion_members_request_operations_inner'
require 'openapi_client/models/update_supergroups_group_id_inclusion_members_request_operations_inner_value_inner'
require 'openapi_client/models/user'
require 'openapi_client/models/user_address'
require 'openapi_client/models/user_name'
require 'openapi_client/models/user_phone_number'
require 'openapi_client/models/user_photo'
require 'openapi_client/models/work_location'
require 'openapi_client/models/worker'
require 'openapi_client/models/worker_location'

# APIs
require 'openapi_client/api/companies_api'
require 'openapi_client/api/custom_fields_api'
require 'openapi_client/api/custom_object_fields_api'
require 'openapi_client/api/custom_object_records_api'
require 'openapi_client/api/custom_objects_api'
require 'openapi_client/api/departments_api'
require 'openapi_client/api/employment_types_api'
require 'openapi_client/api/entitlements_api'
require 'openapi_client/api/me_api'
require 'openapi_client/api/object_categories_api'
require 'openapi_client/api/supergroups_api'
require 'openapi_client/api/teams_api'
require 'openapi_client/api/users_api'
require 'openapi_client/api/work_locations_api'
require 'openapi_client/api/workers_api'

module OpenapiClient
  class << self
    # Customize default settings for the SDK using block.
    #   OpenapiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
