=begin
#Rippling Platform API

#Documentation for the Rippling Platform API.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'cgi'

module OpenapiClient
  class MeApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Retrieve my SSO information
    # SSO information of the current user  - Requires: `API Tier 1`  - Expandable fields: `company`
    # @param [Hash] opts the optional parameters
    # @option opts [String] :expand 
    # @return [SSOMe]
    def list_sso_me(opts = {})
      data, _status_code, _headers = list_sso_me_with_http_info(opts)
      data
    end

    # Retrieve my SSO information
    # SSO information of the current user  - Requires: &#x60;API Tier 1&#x60;  - Expandable fields: &#x60;company&#x60;
    # @param [Hash] opts the optional parameters
    # @option opts [String] :expand 
    # @return [Array<(SSOMe, Integer, Hash)>] SSOMe data, response status code and response headers
    def list_sso_me_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: MeApi.list_sso_me ...'
      end
      # resource path
      local_var_path = '/sso-me'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'expand'] = opts[:'expand'] if !opts[:'expand'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'SSOMe'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['OAuth2Production', 'BearerTokenProduction']

      new_options = opts.merge(
        :operation => :"MeApi.list_sso_me",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: MeApi#list_sso_me\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
